/**
 * GENERATED. Do not edit.
 *
 * Written by scripts/build-coverage.ts from suppliers/esimaccess-coverage-2026-09-14.csv,
 * which was read from the eSIM Access partner console on 14 September 2026.
 * Change the CSV and run the script; promises.test.ts fails if they disagree.
 */

export const READ_ON = "14 September 2026";
export const SOURCE = "esimaccess-coverage-2026-09-14.csv";
export const GROUPS = 36;

export const COUNTRIES: ReadonlyArray<readonly [string, string]> = [
  ["Afghanistan", "apac"],
  ["Aland Islands", "europe"],
  ["Albania", "europe"],
  ["Algeria", "mea"],
  ["Andorra", "europe"],
  ["Angola", "mea"],
  ["Anguilla", "americas"],
  ["Antigua and Barbuda", "americas"],
  ["Argentina", "americas"],
  ["Armenia", "mea"],
  ["Aruba", "americas"],
  ["Australia", "apac"],
  ["Austria", "europe"],
  ["Azerbaijan", "mea"],
  ["Bahamas", "americas"],
  ["Bahrain", "mea"],
  ["Bangladesh", "apac"],
  ["Barbados", "americas"],
  ["Belarus", "europe"],
  ["Belgium", "europe"],
  ["Belize", "americas"],
  ["Benin", "mea"],
  ["Bermuda", "americas"],
  ["Bhutan", "apac"],
  ["Bolivia", "americas"],
  ["Bonaire", "americas"],
  ["Bosnia and Herzegovina", "europe"],
  ["Botswana", "mea"],
  ["Brazil", "americas"],
  ["Brunei Darussalam", "apac"],
  ["Bulgaria", "europe"],
  ["Burkina Faso", "mea"],
  ["Cambodia", "apac"],
  ["Cameroon", "mea"],
  ["Canada", "americas"],
  ["Cape Verde", "mea"],
  ["Cayman Islands", "americas"],
  ["Central African Republic", "mea"],
  ["Chad", "mea"],
  ["Chile", "americas"],
  ["China mainland", "apac"],
  ["Colombia", "americas"],
  ["Costa Rica", "americas"],
  ["Cote d'Ivoire", "mea"],
  ["Croatia", "europe"],
  ["Curacao", "americas"],
  ["Cyprus", "europe"],
  ["Czech Republic", "europe"],
  ["Democratic Republic of the Congo", "mea"],
  ["Denmark", "europe"],
  ["Dominica", "americas"],
  ["Dominican Republic", "americas"],
  ["Ecuador", "americas"],
  ["Egypt", "mea"],
  ["El Salvador", "americas"],
  ["Estonia", "europe"],
  ["Eswatini", "mea"],
  ["Ethiopia", "mea"],
  ["Faroe Islands", "europe"],
  ["Fiji", "apac"],
  ["Finland", "europe"],
  ["France", "europe"],
  ["French Guiana", "americas"],
  ["French Polynesia", "apac"],
  ["Gabon", "mea"],
  ["Gambia", "mea"],
  ["Georgia", "mea"],
  ["Germany", "europe"],
  ["Ghana", "mea"],
  ["Gibraltar", "europe"],
  ["Greece", "europe"],
  ["Greenland", "europe"],
  ["Grenada", "americas"],
  ["Guadeloupe", "americas"],
  ["Guam", "apac"],
  ["Guatemala", "americas"],
  ["Guernsey", "europe"],
  ["Guinea", "mea"],
  ["Guinea-Bissau", "mea"],
  ["Guyana", "americas"],
  ["Haiti", "americas"],
  ["Honduras", "americas"],
  ["Hong Kong (China)", "apac"],
  ["Hungary", "europe"],
  ["Iceland", "europe"],
  ["India", "apac"],
  ["Indonesia", "apac"],
  ["Iraq", "mea"],
  ["Ireland", "europe"],
  ["Isle of Man", "europe"],
  ["Israel", "mea"],
  ["Italy", "europe"],
  ["Jamaica", "americas"],
  ["Japan", "apac"],
  ["Jersey", "europe"],
  ["Jordan", "mea"],
  ["Kazakhstan", "apac"],
  ["Kenya", "mea"],
  ["Kosovo", "europe"],
  ["Kuwait", "mea"],
  ["Kyrgyzstan", "apac"],
  ["Laos", "apac"],
  ["Latvia", "europe"],
  ["Liberia", "mea"],
  ["Libya", "mea"],
  ["Liechtenstein", "europe"],
  ["Lithuania", "europe"],
  ["Luxembourg", "europe"],
  ["Macao (China)", "apac"],
  ["Madagascar", "mea"],
  ["Malawi", "mea"],
  ["Malaysia", "apac"],
  ["Maldives", "apac"],
  ["Mali", "mea"],
  ["Malta", "europe"],
  ["Martinique", "americas"],
  ["Mauritania", "mea"],
  ["Mauritius", "mea"],
  ["Mayotte", "mea"],
  ["Mexico", "americas"],
  ["Moldova", "europe"],
  ["Monaco", "europe"],
  ["Mongolia", "apac"],
  ["Montenegro", "europe"],
  ["Montserrat", "americas"],
  ["Morocco", "mea"],
  ["Mozambique", "mea"],
  ["Nauru", "apac"],
  ["Nepal", "apac"],
  ["Netherlands", "europe"],
  ["Netherlands Antilles", "americas"],
  ["New Zealand", "apac"],
  ["Nicaragua", "americas"],
  ["Niger", "mea"],
  ["Nigeria", "mea"],
  ["North Macedonia", "europe"],
  ["Norway", "europe"],
  ["Oman", "mea"],
  ["Pakistan", "apac"],
  ["Panama", "americas"],
  ["Papua New Guinea", "apac"],
  ["Paraguay", "americas"],
  ["Peru", "americas"],
  ["Philippines", "apac"],
  ["Poland", "europe"],
  ["Portugal", "europe"],
  ["Puerto Rico", "americas"],
  ["Qatar", "mea"],
  ["Republic of the Congo", "mea"],
  ["Reunion", "mea"],
  ["Romania", "europe"],
  ["Russia", "europe"],
  ["Rwanda", "mea"],
  ["Saint Barthelemy", "americas"],
  ["Saint Kitts and Nevis", "americas"],
  ["Saint Lucia", "americas"],
  ["Saint Martin", "americas"],
  ["Saint Vincent and the Grenadines", "americas"],
  ["Samoa", "apac"],
  ["San Marino", "europe"],
  ["Saudi Arabia", "mea"],
  ["Senegal", "mea"],
  ["Serbia", "europe"],
  ["Seychelles", "mea"],
  ["Sierra Leone", "mea"],
  ["Singapore", "apac"],
  ["Slovakia", "europe"],
  ["Slovenia", "europe"],
  ["South Africa", "mea"],
  ["South Korea", "apac"],
  ["Spain", "europe"],
  ["Sri Lanka", "apac"],
  ["Sudan", "mea"],
  ["Suriname", "americas"],
  ["Sweden", "europe"],
  ["Switzerland", "europe"],
  ["Taiwan (China)", "apac"],
  ["Tajikistan", "apac"],
  ["Tanzania", "mea"],
  ["Thailand", "apac"],
  ["Tonga", "apac"],
  ["Trinidad and Tobago", "americas"],
  ["Tunisia", "mea"],
  ["Turkey", "europe"],
  ["Turks and Caicos Islands", "americas"],
  ["Uganda", "mea"],
  ["Ukraine", "europe"],
  ["United Arab Emirates", "mea"],
  ["United Kingdom", "europe"],
  ["United States", "americas"],
  ["Uruguay", "americas"],
  ["Uzbekistan", "apac"],
  ["Vanuatu", "apac"],
  ["Vatican City", "europe"],
  ["Venezuela", "americas"],
  ["Vietnam", "apac"],
  ["Virgin Islands- British", "americas"],
  ["Zambia", "mea"],
  ["Zimbabwe", "mea"],
];
