/**
 * Generates PLAY-SUBMISSION.md from lib/legal.ts.
 *
 * The point is that the Data Safety answers you type into Play Console and the
 * privacy policy you publish are produced from one source. Writing them
 * separately is how they drift, and a drift between them is the most common
 * privacy-related removal from Google Play — it is treated as a
 * misrepresentation, not a paperwork error.
 *
 * Re-run this whenever lib/legal.ts changes:
 *   npx tsx scripts/gen-play-kit.ts
 */
import fs from "node:fs";
import path from "node:path";
import { brand } from "../src/lib/brand";
import { DATA_INVENTORY, LEGAL_ENTITY } from "../src/lib/legal";

const out: string[] = [];
const w = (s = "") => out.push(s);

w(`# Play Console submission kit — ${brand.name}`);
w();
w(`> **Generated from \`web/src/lib/legal.ts\`.** Do not edit this file by hand —`);
w(`> edit the source and re-run \`npx tsx scripts/gen-play-kit.ts\`. The whole`);
w(`> point is that these answers and the published privacy policy cannot drift`);
w(`> apart, because Play treats a mismatch as a misrepresentation.`);
w();
w(`Effective ${LEGAL_ENTITY.effectiveDate} · package \`${brand.androidPackage}\``);
w();
w("---");
w();

w("## Before you open Play Console");
w();
w("These must be live and reachable, because reviewers click them:");
w();
w(`- [ ] \`https://${brand.domain}/privacy\``);
w(`- [ ] \`https://${brand.domain}/terms\``);
w(`- [ ] \`https://${brand.domain}/refunds\``);
w(`- [ ] \`https://${brand.domain}/app-ads.txt\` — must be the **apex** domain,`);
w(`      matching the developer website on your listing exactly`);
w(`- [ ] \`${LEGAL_ENTITY.contactEmail}\` — a real inbox someone reads`);
w();
w("---");
w();

w("## Store listing");
w();
w("| Field | Value |");
w("|---|---|");
w(`| App name | ${brand.name} — Free eSIM Data |`);
w(`| Short description | ${brand.shortDescription} |`);
w("| Category | Travel & Local |");
w("| Content rating | Everyone |");
w(`| Contains ads | **Yes** — not declaring this is a removable offence |`);
w("| In-app purchases | **No**, for the first release (free tier only) |");
w(`| Developer website | \`https://${brand.domain}\` |`);
w(`| Privacy policy | \`https://${brand.domain}/privacy\` |`);
w(`| Support email | ${LEGAL_ENTITY.contactEmail} |`);
w();
w("Full listing copy is in `brand/BRAND.md`.");
w();
w("---");
w();

w("## Data safety — answers, field by field");
w();
w("### Overview questions");
w();
w("| Question | Answer |");
w("|---|---|");
w("| Does your app collect or share any of the required user data types? | **Yes** |");
w("| Is all of the user data collected by your app encrypted in transit? | **Yes** — HTTPS only, and the `.com` is served over TLS |");
w("| Do you provide a way for users to request that their data is deleted? | **Yes** — by email, see the privacy policy |");
w();

w("### Data types");
w();
w("| Category | Type | Collected | Shared | Required | Purpose |");
w("|---|---|---|---|---|---|");
for (const d of DATA_INVENTORY) {
  const shared = d.shared ? `Yes — ${d.sharedWith}` : "No";
  const required = d.optional ? "Optional" : "Required";
  const purpose = d.purpose.replace(/\s+/g, " ").slice(0, 90).trim();
  w(
    `| ${d.playCategory} | ${d.playType} | ${d.collected ? "Yes" : "No"} | ${shared} | ${required} | ${purpose}… |`
  );
}
w();
w("**Purpose checkboxes to tick in the form**, mapped from the above:");
w();
w("- *App functionality* — account ID, country, eSIM identifier");
w("- *Advertising or marketing* — advertising ID");
w("- *Fraud prevention, security and compliance* — earning history, account ID");
w();
w("Do **not** tick *Analytics* or *Personalisation* unless you add tools that");
w("genuinely do those things. Over-declaring is not the safe option — it has to");
w("match the policy, and the policy says what the code does.");
w();
w("---");
w();

w("## Ads declaration");
w();
w("Play asks how ads are shown. The answers:");
w();
w("- Ad format: **Rewarded video**, user-initiated only");
w("- Ads are never shown outside the app, on the lock screen, or in notifications");
w("- No interstitials on launch");
w("- Ads are not shown to users under 13 — set the AdMob content rating");
w("  accordingly and complete the target-audience section as adults only");
w();
w("---");
w();

w("## Things reviewers reject this category for");
w();
w("Worth reading once before you submit, because each of these costs a review cycle:");
w();
w("1. **Minimum functionality.** Apps that look like a website in a wrapper get");
w("   rejected. This one clears the bar — native rewarded ads and the system");
w("   eSIM install handoff — but say so in the listing rather than describing it");
w("   as a web app.");
w("2. **Privacy policy that 404s or does not mention ads.** Both are instant");
w("   rejections. Ours covers AdMob explicitly.");
w("3. **Undeclared ads.** You have rewarded video. Tick the box.");
w("4. **Data Safety disagreeing with the privacy policy.** Solved structurally —");
w("   both come from `lib/legal.ts`.");
w("5. **Health or emergency claims.** Never imply the eSIM can be relied on for");
w("   emergency calls. It is data-only, and the terms say so explicitly.");
w();
w("---");
w();

w("## Release build");
w();
w("```powershell");
w("flutter build appbundle `");
w(`  --dart-define=API_BASE=https://${brand.domain} \``);
w("  --dart-define=ADMOB_REWARDED_ID=<your real rewarded unit>");
w("```");
w();
w("Two irreversible things — get them right the first time:");
w();
w("- **Keystore.** Back it up somewhere you will still have in five years. Lose");
w("  it and you can never update the app.");
w(`- **\`applicationId\`.** \`${brand.androidPackage}\` is immutable once published.`);
w("  Changing it later means a new listing with zero installs and zero reviews.");
w();
w("---");
w();

w("## Sequence, and why this order");
w();
w("1. Deploy the web app so the legal pages resolve");
w("2. Submit to Play — **internal testing first**, then production");
w("3. Once live, create the AdMob app and link it to the Play listing");
w("4. Create a rewarded ad unit; set SSV callback to");
w(`   \`https://${brand.domain}/api/ads/ssv\``);
w(`5. Publish \`app-ads.txt\`; allow 24h for the crawl`);
w("6. Swap the test ad unit for the real one and ship an update");
w();
w("**AdMob will not serve ads on an unpublished app**, so step 2 gates every");
w("dollar this business will ever make. It is the reason to submit before");
w("payments exist rather than after.");
w();
w("---");
w();

w("## Not legal advice");
w();
w("These documents were drafted against what the code actually does, which puts");
w("them ahead of most templates. They are still drafts. The refund policy and the");
w("Australian Consumer Law sections sit next to an unresolved question about");
w("whether reselling roaming data makes you a registrable carriage service");
w("provider — get a lawyer to read both before you take money.");
w();

const target = path.join(__dirname, "..", "..", "PLAY-SUBMISSION.md");
fs.writeFileSync(target, out.join("\n"), "utf8");
console.log(`Wrote ${path.resolve(target)} (${out.length} lines)`);
