/**
 * Generates PLAY-SUBMISSION.md from lib/legal.ts.
 *
 * The point is that the Data Safety answers you type into Play Console and the
 * privacy policy you publish are produced from one source. Writing them
 * separately is how they drift, and a drift between them is the most common
 * privacy-related removal from Google Play — it is treated as a
 * misrepresentation, not a paperwork error.
 *
 * Re-run this whenever lib/legal.ts changes:
 *   npx tsx scripts/gen-play-kit.ts
 */
import fs from "node:fs";
import path from "node:path";
import { brand } from "../src/lib/brand";
import { DATA_INVENTORY, LEGAL_ENTITY } from "../src/lib/legal";

const out: string[] = [];
const w = (s = "") => out.push(s);

w(`# Play Console submission kit — ${brand.name}`);
w();
w(`> **Generated from \`web/src/lib/legal.ts\`.** Do not edit this file by hand —`);
w(`> edit the source and re-run \`npx tsx scripts/gen-play-kit.ts\`. The whole`);
w(`> point is that these answers and the published privacy policy cannot drift`);
w(`> apart, because Play treats a mismatch as a misrepresentation.`);
w();
w(`Effective ${LEGAL_ENTITY.effective.privacy} · package \`${brand.androidPackage}\``);
w();
w("---");
w();

w("## Before you open Play Console");
w();
w("These must be live and reachable, because reviewers click them:");
w();
w(`- [ ] \`https://${brand.domain}/privacy\``);
w(`- [ ] \`https://${brand.domain}/terms\``);
w(`- [ ] \`https://${brand.domain}/refunds\``);
w(`- [ ] \`${LEGAL_ENTITY.contactEmail}\` — a real inbox someone reads`);
w();
w("---");
w();

w("## Store listing");
w();
w("| Field | Value |");
w("|---|---|");
w(`| App name | ${brand.name} |`);
w(`| Short description | ${brand.shortDescription} |`);
w("| Category | Travel & Local |");
w("| Content rating | Everyone |");
w(`| Contains ads | **No** — there is no ad SDK in the build |`);
w("| In-app purchases | **No** — plans are bought on the web, not through Play |");
w(`| Developer website | \`https://${brand.domain}\` |`);
w(`| Privacy policy | \`https://${brand.domain}/privacy\` |`);
w(`| Support email | ${LEGAL_ENTITY.contactEmail} |`);
w();
w("Full listing copy is in `brand/BRAND.md`.");
w();
w("---");
w();

w("## Data safety — answers, field by field");
w();
w("### Overview questions");
w();
w("| Question | Answer |");
w("|---|---|");
w("| Does your app collect or share any of the required user data types? | **Yes** |");
w("| Is all of the user data collected by your app encrypted in transit? | **Yes** — HTTPS only, and the `.com` is served over TLS |");
w("| Do you provide a way for users to request that their data is deleted? | **Yes** — by email, see the privacy policy |");
w();

w("### Data types");
w();
w("| Category | Type | Collected | Shared | Required | Purpose |");
w("|---|---|---|---|---|---|");
for (const d of DATA_INVENTORY) {
  const shared = d.shared ? `Yes — ${d.sharedWith}` : "No";
  const required = d.optional ? "Optional" : "Required";
  const purpose = d.purpose.replace(/\s+/g, " ").slice(0, 90).trim();
  w(
    `| ${d.playCategory} | ${d.playType} | ${d.collected ? "Yes" : "No"} | ${shared} | ${required} | ${purpose}… |`
  );
}
w();
w("**Purpose checkboxes to tick in the form**, mapped from the above:");
w();
w("- *App functionality* — account ID, country, eSIM identifier");
w("- *Purchase history* — what was bought, for support and as the accounting record");
w("- *Fraud prevention, security and compliance* — purchase history, account ID");
w();
w("Do **not** tick *Analytics* or *Personalisation* unless you add tools that");
w("genuinely do those things. Over-declaring is not the safe option — it has to");
w("match the policy, and the policy says what the code does.");
w();
w("---");
w();

w("## Things reviewers reject this category for");
w();
w("Worth reading once before you submit, because each of these costs a review cycle:");
w();
w("1. **Minimum functionality.** Apps that look like a website in a wrapper get");
w("   rejected. What clears the bar here is the system eSIM install handoff and");
w("   the plan library, so describe those in the listing rather than describing");
w("   it as a web app.");
w("2. **Payments.** Plans are bought on the web and the app links out to a");
w("   browser rather than embedding checkout. Play's Payments policy exempts");
w("   purchases consumed outside a Play distributed app, and connectivity is");
w("   consumed by the handset modem. Two rules keep that true and both are");
w("   load bearing: never open checkout in a webview, and never gate an app");
w("   feature behind a purchase.");
w("3. **Data Safety disagreeing with the privacy policy.** Solved structurally:");
w("   both come from `lib/legal.ts`.");
w("4. **Declaring things the build does not do.** This kit used to declare");
w("   rewarded video ads and name the app \"Free eSIM Data\". There is no ad SDK");
w("   in the build and nothing about the product is free. Declaring ads you do");
w("   not serve is a misrepresentation in the same way that failing to declare");
w("   ads you do serve is, and the listing name has to describe the product.");
w("5. **Health or emergency claims.** Never imply the eSIM can be relied on for");
w("   emergency calls. It is data only, and the terms say so explicitly.");
w();
w("---");
w();

w("## Release build");
w();
w("```bash");
w("cd web");
w("npm run build");
w("npx cap sync android");
w("cd android && ./gradlew bundleRelease");
w("```");
w();
w("Two irreversible things, so get them right the first time:");
w();
w("- **Keystore.** Back it up somewhere you will still have in five years. Lose");
w("  it and you can never update the app.");
w(`- **\`applicationId\`.** \`${brand.androidPackage}\` is immutable once published.`);
w("  Changing it later means a new listing with zero installs and zero reviews.");
w();
w("Never ship a `BILBY_SHRINK=false` build to Play.");
w();
w("---");
w();

w("## Sequence, and why this order");
w();
w("1. Deploy the web app so the legal pages resolve. Play checks them.");
w("2. Submit to Play, internal testing first, then production.");
w("3. Keep the app in review while the shop is still closed. The listing can be");
w("   approved before `CHECKOUT_OPEN` is set; a reviewer who cannot buy anything");
w("   is not a problem, a reviewer who buys something simulated is.");
w();
w("---");
w();

w("## Not legal advice");
w();
w("These documents were drafted against what the code actually does, which puts");
w("them ahead of most templates. They are still drafts. The refund policy and the");
w("Australian Consumer Law sections sit next to an unresolved question about");
w("whether reselling roaming data makes you a registrable carriage service");
w("provider — get a lawyer to read both before you take money.");
w();

const target = path.join(__dirname, "..", "..", "PLAY-SUBMISSION.md");
fs.writeFileSync(target, out.join("\n"), "utf8");
console.log(`Wrote ${path.resolve(target)} (${out.length} lines)`);
